---

- name: Delete existing {{ collector.ovs.path }} folder 
  file:
    path: "{{ collector.ovs.path }}"
    state: absent
  become: true

- name: Create {{ collector.ovs.path }} folder 
  file:
    path: "{{ collector.ovs.path }}"
    state: directory
  become: true

- name: Install OVS DPDK rules from {{ ovs_accel.ovs.bridge.name }} {{ ovs_accel.ovs.params.rules.path }}/{{ ovs_accel.ovs.params.rules.ruleset }}
  shell: |
    ovs-ofctl add-flows {{ ovs_accel.ovs.bridge.name }} {{ ovs_accel.ovs.params.rules.path }}/{{ ovs_accel.ovs.params.rules.ruleset }}
  become: true

- name: Start the OVS PMD logger using {{ ovs_logging.script.dest }}
  import_tasks: roles/logging/tasks/start.yml
  tags: start-logger