---

- name: Kill the OVS PMD logger
  import_tasks: roles/logging/tasks/stop.yml
  tags: stop-logger

- name: Save final stats to {{ collector.ovs.path }}/ovs-log-complete.log
  shell: |
    ovs-appctl dpif-netdev/pmd-perf-show > {{ collector.ovs.path }}/ovs-log-complete.log
  ignore_errors: true
  become: true

- name: Uninstall OVS rules
  shell: |
    ovs-ofctl del-flows {{ ovs_dpdk.ovs.bridge.name }}
  ignore_errors: true
  become: true
