---

# https://ericsysmin.com/2019/06/20/how-to-loop-blocks-of-code-in-ansible/
- name: Run experiment for OLS pipeline as a demo
  hosts: all
  gather_facts: true
  vars_files:
    - vars/passwords.yml
    - vars/main.yml

  tasks:
    - name: Demo loop
      include_tasks: gvs_demo_tasks.yml