---

- name: Kill the OVS PMD logger
  shell: |
    pkill -f {{ ovs_logging.script.dest }}
  ignore_errors: true
  become: true

- name: Kill the InfluxDB logger
  shell: |
    pkill -f {{ influx_db.script.dest }}
  ignore_errors: true
  become: true
