---

- name: Delete existing {{ collector.ovs.path }} folder 
  file:
    path: "{{ collector.ovs.path }}"
    state: absent
  become: true

- name: Create {{ collector.ovs.path }} folder 
  file:
    path: "{{ collector.ovs.path }}"
    state: directory
  become: true

- name: Install GVS DPDK rules from {{ gvs.ovs.bridge.name }} {{ gvs.ovs.params.rules.path }}/{{ gvs.ovs.params.rules.ruleset }}
  shell: |
    ovs-ofctl add-flows {{ gvs.ovs.bridge.name }} {{ gvs.ovs.params.rules.path }}/{{ gvs.ovs.params.rules.ruleset }}
  become: true

- name: Start the GVS PMD logger using {{ ovs_logging.script.dest }}
  import_tasks: roles/logging/tasks/start.yml
  tags: start-logger