---

- name: Download Mellanox OFED .tgz archive
  get_url:
    url: "https://content.mellanox.com/ofed/MLNX_OFED-24.10-2.1.8.0/{{ mlnx_version }}-ubuntu20.04-x86_64.tgz"
    dest: "{{ mlnx_path }}.tgz"
    mode: '0644'

- name: Extract .tgz archive
  unarchive:
    src: "{{ mlnx_path }}.tgz"
    dest: "/home/{{ user }}/tools"
    remote_src: yes


- name: Run Mellanox OFED install script
  command: "./mlnxofedinstall --dpdk {{ ansible_kernel }} --without-fw-update --force"
  args:
    chdir: "{{ mlnx_path }}"
  become: yes


- name: Clean up OFED installation files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ mlnx_path }}.tgz"
    - "{{ mlnx_path }}"


- name: Register firmware info
  shell: |
    ibv_devinfo
  register: ibv_devinfo

- name: Verify firmware info
  debug:
    var: ibv_devinfo


# The rpcrdma module is a Linux kernel component that implements RPC 
# (Remote Procedure Call) over RDMA (Remote Direct Memory Access) transport,
# commonly known as NFS over RDMA or NFSoRDMA. It allows NFS (Network File System)
# traffic to use high-performance RDMA networks like InfiniBand or RoCE 
# (RDMA over Converged Ethernet) instead of traditional TCP/IP, providing
# significantly lower latency and higher throughput by enabling direct 
# memory-to-memory data transfers between systems without CPU involvement. 
# This module acts as a bridge between the NFS subsystem and RDMA hardware, 
# which is why it depends on the rdma_cm (RDMA Connection Manager) module 
# and why NFS services often prevent RDMA modules from being unloaded cleanly.

- name: Force remove rpcrdma module
  command: rmmod rpcrdma
  become: yes
  ignore_errors: yes


- name: Restart openibd service
  command: /etc/init.d/openibd restart
  become: yes
