---

- name: Create "{{ collector.destination.path }}" folder 
  file:
    path: "{{ collector.destination.path }}"
    state: directory
  become: true

- name: Synchronize {{ collector.ovs.path }} folder from GVS to COLLECTOR
  synchronize:
    src: "{{ collector.ovs.path }}"
    dest: "{{ collector.destination.path }}"
    mode: push
  delegate_to: "GVS"
  become: true

- name: Synchronize {{ collector.tgen.path }} file from TGEN to COLLECTOR
  synchronize:
    src: "{{ collector.tgen.path }}"
    dest: "{{ collector.destination.path }}"
    mode: push
  delegate_to: "TGEN"
  become: true