---

- name: Collect GVS and TGen logs to COLLECTOR
  import_tasks: roles/collector/tasks/collect.yml
  tags: collect-logs

- name: Discard logs from COLLECTOR
  import_tasks: roles/collector/tasks/discard.yml
  tags: discard-logs